export class Usuario{
    usuario_id:number;
    usuario_nombres:string;
    usuario_apellidos:string;
    usuario_correo:string;
    usuario_rol:string;
    usuario_estado:string;
    constructor(
        usuario_id:number,
        usuario_nombres:string,
        usuario_apellidos:string,
        usuario_correo:string,
        usuario_rol:string,
        usuario_estado:string
    ){
        this.usuario_id=usuario_id;
        this.usuario_nombres=usuario_nombres;
        this.usuario_apellidos=usuario_apellidos;
        this.usuario_correo=usuario_correo;
        this.usuario_rol=usuario_rol
        this.usuario_estado=usuario_estado;
    }
}
